### ISSUE TITLE
Old libs in 7.1 Setup

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Matlab-Toolbox#13]
7.1 toolbox installs not the latest version of SimModel, SimModelComp, FuncParser, SimModelSolver (and maybe also other DLLs and XMLs).
Those are installed under **_[Toolbox_InstallDir]\lib_**

**Comment by msevestre** [comment]
This is the absolute correct behavior. When libs are updated, a task should be created in all dependent project that require the updated version

**Comment by msevestre** [comment]
@Yuri05 As far as I can tell, FuncParser and SimModelSolver are updated to latest (2.0.0.1, only one version of the component)
