### ISSUE TITLE
MoBiSettings: call without parameters sets wrong default paths

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/Matlab-Toolbox#15]
When calling MoBiSettings without parameters on a fresh installation, the paths in the global variable MOBI_SETTINGS are not set properly. It seems to remember some C:\VSS path.

**Comment by Yuri05** [comment]
Cannot reproduce. Calling MoBiSettings without arguments sets correct paths:

<img width="567" alt="mobisettings" src="https://cloud.githubusercontent.com/assets/25061876/26254110/bd629e98-3cb5-11e7-9a95-247a7f1b3894.png">

**Comment by Yuri05** [comment]
@UlrichSi Is this still an issue?

**Comment by UlrichSi** [comment]
It has to be installed on a fresh Windows, e.g., a VM, which has never been used to install MoBi before. If it is not reproducible there, it may have been a temporary issue.

**Comment by Yuri05** [comment]
Cannot reproduce with 7.4. Closing.
Please reopen if you still face the issue.
