### ISSUE TITLE
Adjust population runner

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Matlab-Toolbox#24]
Matlab population runner must be adjusted to reflect changes in Open-Systems-Pharmacology/PK-Sim#170

**Comment by msevestre** [comment]
@rwmcintosh , @Yuri05 
I don't think this is required anymore. We will not change the way we create the parameter for cluster export

@rwmcintosh Please close this issue once  Open-Systems-Pharmacology/PK-Sim#170 is fixed

**Comment by rwmcintosh** [comment]
That's not required now that units are not included with the export for cluster option
