### ISSUE TITLE
Error while setting the trees

### ISSUE THREAD

**Issue by mlcraig** [Open-Systems-Pharmacology/Matlab-Toolbox#31]
I'm trying to open a PK Sim/MoBi project in Matlab using the MoBi Matlab toolbox. I am running a 32 bit version of Matlab (2015b). My workflow is to create the project in PKSim, then export a .xml file (in either PK Sim or MoBi), run generateMatlabCodeForXML.m and then select the relevant .xml file in the gui. 

When I select the export project .xml file, I receive the error "Error while setting the Trees! Undefined function 'getDescriptionArrays' for input arguments of type 'double' ". I don't have an m-file called getDescriptionArrays in the code folder where the toolbox is located so that explains the error, should there be one or am I not calling things in the proper order?

**Comment by msevestre** [comment]
@KatrinCoboeken Any idea?

**Comment by KatrinCoboeken** [comment]
This function should be in the folder src\code\auxiliaries.  
Did you also add the  subfolder auxiliaries is to the path or only the code folder without subfolders?

**Comment by msevestre** [comment]
@mlcraig How did you install the toolbox? 
The file you mentioned is under the /auxiliaries folder

See source file here: https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox/blob/develop/src/code/auxiliaries/getDescriptionArrays.m

**Comment by mlcraig** [comment]
So sorry, I didn't actually poke around in the subfolders beyond the code one so thank you for pointing that out. 

I suppose it's not entirely clear to me what the proper procedure is for installing/running the toolbox, I am reading through the manual, are there other instructions? I was just navigating to the code folder and running generateMatlabCodeForXML.m from the command window.

**Comment by msevestre** [comment]
@mlcraig There is definitely some room for improvement, e.g. a step by step instructions on how to get going with the toolbox. Any help would be appreciated here :)

**Comment by mlcraig** [comment]
@msevestre Agreed, it would definitely be helpful!

What I just did to set the path was use the call 'pathtool' from the command window, save the pathdef.m and the code folders in Matlab's startup folder, and then save the path. Is that correct and do I need to do anything further to have things work (should I copy the m-files from the auxiliary folder into the main code folder)? Thanks for the help, sorry for so many questions!

**Comment by mlcraig** [comment]
Sorry again, but now I have a new error, even when trying to run the example xml files provided upon installation. If I select any file in the GUI, I now have the following error:

"Error while setting the Trees! SimulationIndex 1 is not valid. There is none simulation initialized."

Any ideas? I've gone into the generateMatlabCodeForXML.m file and located the line giving the error but I'm not sure how to fix it.

**Comment by msevestre** [comment]
This issue was solved. A new issue was created

**Comment by msevestre** [comment]
@mlcraig I have created an issue to update readme. Please add any comment you might have here. 
Thanks
