### ISSUE TITLE
Update call to MatalbIndividualFactory and MatlabPopulationFactory to use new namespaces

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Matlab-Toolbox#43]

**Comment by msevestre** [comment]
@Yuri05 This is required because Batch objects are now gone

**Comment by msevestre** [comment]
@Yuri05 Actually.
Do you know if it is possible to use properties as object in Matlab? 
e.g. would it be possible to instantiate a snapshot class OriginData which as for example an Age property which is not a double but a Parameter{ Value, Unit}.

**Comment by Yuri05** [comment]
Yes is possible

**Comment by msevestre** [comment]
@Yuri05 This is going to be the task to use when the changes in PKSim are ready

**Comment by msevestre** [comment]
This if fixed I believe in Matlab Core
