### ISSUE TITLE
Simulation error "Unable to resolve Path : "...|...|DrugMass" for Total Drug Mass

### ISSUE THREAD

**Issue by HenrikCordes** [Open-Systems-Pharmacology/Matlab-Toolbox#50]
Dear all,

just installed the latest PK-Sim version. Somehow some of my previous Simulation (form Version 7.1) throw the attached error. Only deleting the simulation and setting up a new one solves the issue. 

Also for new projects in PK-Sim 7.2 this error randomly shows up and the solution is the same as described above. 

![bug](https://user-images.githubusercontent.com/4817133/34070944-6d82391a-e26e-11e7-89fd-2238de4e244e.PNG)

**Comment by msevestre** [comment]
@HenrikCordes: thanks for letting us know. As we were unable to catch this issue in our all tests, would it be possible to provide us with a project that we could use to track down that issue? 

The randomly aspect is what I don't like.... I'd like to understand what's really going on.

Thanks for your help,

**Comment by msevestre** [comment]
Also you are posting this Bug in the Matlab tool box repo. Is there any Matlab involved here?

**Comment by HenrikCordes** [comment]
Dear Michael,

so up to know I delete the simulation and move on. So I do not have the corrupted file at hands. 

I could not reproduce the error, but got another one.
I attached the error message.


It slipped my attention that I was in the Matlab toll box repo. Should I again post the issue in the PK-Sim repo. ?

Kind regards,
Henrik

**Comment by msevestre** [comment]
>It slipped my attention that I was in the Matlab toll box repo. Should I again post the issue in the PK-Sim repo. ?

Yes that would be great. Thanks
