### ISSUE TITLE
Export population results to csv (and PK-Analysis) should export using "," instead of ";"

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Matlab-Toolbox#57]
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/540

PK-Sim will not import outdated files anymore as this function is barely/never used

**Comment by msevestre** [comment]
PS: I am not even sure if this feature was ever used... Idea was to calculate on cluster and import results back to PK-Sim...

**Comment by Yuri05** [comment]
currently no implications on the matlab toolbox
