### ISSUE TITLE
Getting toolbox to work (installing problem): DCI 

### ISSUE THREAD

**Issue by salarrahili** [Open-Systems-Pharmacology/Matlab-Toolbox#85]
Hi,

I am trying to make toolbox works using MATLAB 2016-b. When I use "generateMatlabCodeForXML", I get an error "simulationindex 1 is not valid....". I saw others had this issue, but could not solve the issue lookign at that discussion. 
I used "initSimulation" separately to find the issue. Then, I get this error
 "Error using feval Undefined function 'DCIMatlabR2017b6_1' for input arguments of type 'char'." 
I believe the issue is not having the updated DCI, but not sure how to update it. 

Thanks,

**Comment by StephanSchaller** [comment]
OSPS 7.3 (32bit) only works with 32 bit Matlab (<= 2015b).
The next release will be 64 bit.

hope this helps,
Cheers, Stephan

**Comment by salarrahili** [comment]
Hi Stephan,

Thanks for your response.
In MobiSetting file, it is mentioned that  " 64bit platform for DCIMatlabR2017b6_1 " must be used, so I was thinking that 2017-b works as well. Is there any timeline for that release?
I am wondering if it would be better for me to switch to R or MATLAB 32bit!

Best,
Salar Rahili

**Comment by StephanSchaller** [comment]
What release of OSPS have you installed?

**Comment by salarrahili** [comment]
Version 7.3.0.

**Comment by StephanSchaller** [comment]
Have you done a separate download / install of the MoBi Matlab Toolbox?

**Comment by salarrahili** [comment]
I believed that the full set up of OSPS will also install the toolbox ( at least some of those files are there). Is there an installing procedure for toolbox? or I must copy paste the files from "Open-Systems-Pharmacology/Matlab-Toolbox" there?

**Comment by Yuri05** [comment]
@salarrahili OSP Suite setup includes the Matlab-Toolbox. No further installation needed. As already answered by @StephanSchaller OSP Suite 7.3 works only with 32 bit versions of Matlab.

So for now you have the following options:
* Wait for the next OSP Release 7.4 (scheduled for this year)
* Install a 32 bit version of Matlab (which means you will need a Matlab version R2015b or below)
* Install a 7.4 version of the OSP Matlab toolbox parallel to your current version (this version is not released yet, so use it **_on your own risk_**). You can find the setup [here](https://ci.appveyor.com/project/open-systems-pharmacology-ci/matlab-toolbox/builds/18750198/artifacts).

**Comment by salarrahili** [comment]
Thanks @Yuri05 and @StephanSchaller for your responses. 

I tried option 3, and it does not work.
 'C:\Open Systems Pharmacology\MoBi Toolbox for Matlab
7.4\lib\DCIMatlabR2017b6_1.mexw64' is not a valid shared library.."
I still have problem with feval function in initSimulation. 

I will try to find an old MATLAB to see if it works with that.

**Comment by salarrahili** [comment]
Update: MATLAB 2013-b (32bit) worked. Thanks again.

**Comment by Yuri05** [comment]
Great. Closing the issue. Please reopen if you face any further problems here.

**Comment by msevestre** [comment]
@yuri05 any idea why option 3 didn't work? Shouldn't we look at that?

**Comment by StephanSchaller** [comment]
But should using the 64bit Tooblox with 7.3 OSPS install work?
@PavelBal, does your 7.4 install also work with the 7.4 Toolbox and Matlab 2017b?

**Comment by Yuri05** [comment]
>any idea why option 3 didn't work? 

Probably VC++2017_x64 was not installed on the system. Will be installed with the full suite setup

>But should using the 64bit Tooblox with 7.3 OSPS install work?

Matlab-Toolbox does not rely on the installed OSP Suite - except for some functionality like CreateIndividual/Population. Thus apart from those exceptions it might work also standalone.

**Comment by PavelBal** [comment]
>does your 7.4 install also work with the 7.4 Toolbox and Matlab 2017b?

I do not have a complete 7.4 installation, only MoBi.
