### ISSUE TITLE
OSP 7.4 generateMatlabCodeForXML giving errors

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Matlab-Toolbox#93]
Hi, 
I have a trouble with the generateMatlabCodeForXML on all xml files in my Matlab (R2018b). I tried opening some old xml files too using the command but I am always getting the following error:

**Error while setting the trees!
Reference to non-existent field 'InputTab'.**

Anyone encountered this? How to resolve this?
![capture](https://user-images.githubusercontent.com/13007976/51978792-7c8a4000-248b-11e9-92bb-b6bc67dbe96f.PNG)

I have also taken the necessary steps described in the user template update in the osp version 7.4

**Comment by prvmalik** [comment]
Not a solution but a comment:  I read somewhere (can't recall where) that the MATLAB toolbox is only compatible with R2017a and later versions.  I've had no trouble on 2017a and 2015a - perhaps you could try a previous version of MATLAB.

**Comment by PriKalra** [comment]
Dear Yuri,

For some reason a reinstallation of Matlab helped run everything smooth. I am not having the issue anymore. 

Thank you for the help. 

Best,
Priyata
